//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuesdayMachines.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TuesdayMachines.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;baseGame&quot;:[[-3,-4,-5,-3,-4,-5,-3,-6,-5,-3,-2,-5,-3,-5,-6,-3,-5,-6,-3,-5,-4,-5,-3,-4,-5,-3,-3,-5,-4,-3,-5,-5,-3,-2,-5,-3,-6,-5,-3,-6,-5,-3,-6,-5,-3,-6,-5,-3,-3,-5,-4,-3,-5,-6,-3,-5,-4,-3,-5,-6,-3,-5,-3,-6,-5,-3,-4,-5,-3,-3,-5,-2,-3,-5,-2,-3,-5,-4,-3,-5,-4,-3,-5,-6,-3,-5,-2,-3,-5,-6,-3,-5,-4,-3,-5,-4,-3,-5,-6,-3,-5,-5,-3,-2,-5,-3,-4,-5,-3,-2,-5,-3,-2,-5,-3,-4,-5,-3,-2,-5,-3,-3,-5,-5,-3,-5,-2,-3,-5,-6,-3,-5,-2,-3,-5,-4,-3,-5,-2,-3,-5,-6,-3,-5,-2,-3,-5,-4,-3,-5,-2,-3,-5,-2,-3,-5,-5,-3,-6,-5,-3,-6,-5,-3,-4,-5, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _mayanReelData {
            get {
                return ResourceManager.GetString("_mayanReelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;baseGame&quot;:[[1,1,1,5,5,6,6,4,4,8,8,3,3,2,2,2,8,7,7,7,1,9,9,9,10,10,1,5,5,5,4,0,4,4,2,2,8,1,4,4,4,7,9,10,3,3,3,6,6,6,9,9,9,1,2,3,4,0,5,6,7,8,9,10,1,5,2,8,7,3,5,6],[10,2,2,2,4,7,7,2,8,8,6,6,2,3,8,8,0,9,9,9,3,3,3,1,2,0,7,7,7,7,5,2,9,10,10,7,4,4,1,1,1,9,5,5,1,5,5,8,8,8,2,2,2,5,5,2,9,9,10,7,7,7,2,2,2,7,7,7,1,1,1],[7,8,8,2,0,2,2,6,3,1,9,10,10,10,6,7,7,7,5,5,5,9,1,1,8,4,2,2,7,7,1,1,4,9,4,10,8,1,1,3,9,9,9,1,1,1,0,6,6,8,8,10,10,10,6,6,6,1,2,3,4,5,6,7,8,9,10],[2,2,5,5,4,4,4,7,2,1,1,5,7,7,9,10,6,6,6,7,7,0,7,7,4,4,8,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _x3duelReelData {
            get {
                return ResourceManager.GetString("_x3duelReelData", resourceCulture);
            }
        }
    }
}
